"use client";

import { Check, Copy } from "lucide-react";
import { IconChevronUp, IconChevronDown } from "@tabler/icons-react";
import {
  type ButtonHTMLAttributes,
  type HTMLAttributes,
  type ReactNode,
  forwardRef,
  useCallback,
  useRef,
  useState,
  useLayoutEffect,
  Children,
  cloneElement,
  isValidElement,
} from "react";
import { ScrollArea, ScrollBar } from "@/components/ui/scroll-area";
import { buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { useCopyButton } from "@/lib/use-copy-button";
import { motion } from "motion/react";

export type CodeBlockProps = HTMLAttributes<HTMLElement> & {
  /**
   * Icon of code block
   *
   * When passed as a string, it assumes the value is the HTML of icon
   */
  icon?: ReactNode;

  /**
   * Title of the code block (e.g. filename)
   */
  title?: string;

  /**
   * Allow to copy code with copy button
   *
   * @defaultValue true
   */
  allowCopy?: boolean;

  /**
   * Keep original background color generated by Shiki or Rehype Code
   *
   * @defaultValue false
   */
  keepBackground?: boolean;
};

export const Pre = forwardRef<HTMLPreElement, HTMLAttributes<HTMLPreElement>>(
  ({ className, ...props }, ref) => {
    return (
      <pre
        ref={ref}
        className={cn("p-4 focus-visible:outline-none", className)}
        {...props}
      >
        {props.children}
      </pre>
    );
  }
);

Pre.displayName = "Pre";

export const CodeBlock = forwardRef<HTMLElement, CodeBlockProps>(
  (
    {
      title,
      allowCopy = true,
      keepBackground = false,
      icon,
      children,
      ...props
    },
    ref
  ) => {
    const areaRef = useRef<HTMLDivElement>(null);
    const contentRef = useRef<HTMLPreElement>(null);
    const [isExpanded, setIsExpanded] = useState(false);
    const [shouldCollapse, setShouldCollapse] = useState(false);

    const onCopy = useCallback(() => {
      const pre = areaRef.current?.getElementsByTagName("pre").item(0);

      if (!pre) return;

      const clone = pre.cloneNode(true) as HTMLElement;
      clone.querySelectorAll(".nd-copy-ignore").forEach((node) => {
        node.remove();
      });

      void navigator.clipboard.writeText(clone.textContent ?? "");
    }, []);

    const toggleExpanded = useCallback(() => {
      setIsExpanded(!isExpanded);
    }, [isExpanded]);

    useLayoutEffect(() => {
      if (contentRef.current) {
        const height = contentRef.current.scrollHeight;
        setShouldCollapse(height > 500);
      }
    }, [children]);

    const childWithRef = Children.map(children, (child) => {
      if (isValidElement(child)) {
        return cloneElement(
          child as React.ReactElement<{ ref: React.Ref<HTMLPreElement> }>,
          { ref: contentRef }
        );
      }
      return child;
    });

    return (
      <figure
        ref={ref}
        {...props}
        className={cn(
          "not-prose group p-2 bg-muted border-[#9e9e9e33] outline-none relative my-6 overflow-hidden border text-sm rounded-lg",
          keepBackground && "bg-(--shiki-light-bg) dark:bg-(--shiki-dark-bg)",
          props.className
        )}
      >
        {title ? (
          <div className="flex px-2 flex-row items-center gap-2 bg-muted py-2">
            <figcaption className="flex-1 truncate text-muted-foreground text-xs font-mono">
              {title}
            </figcaption>
            <div className="flex flex-row items-center gap-1">
              <CopyButton className="-me-1" onCopy={onCopy} />
              {shouldCollapse && (
                <ExpandButton
                  isExpanded={isExpanded}
                  toggleExpanded={toggleExpanded}
                />
              )}
            </div>
          </div>
        ) : (
          allowCopy && (
            <CopyButton
              className="absolute right-2 top-2 z-2 backdrop-blur-md"
              onCopy={onCopy}
            />
          )
        )}
        <motion.div
          ref={areaRef}
          className="overflow-hidden bg-[#EDEDED] border rounded-lg "
          initial={false}
          animate={{
            height:
              shouldCollapse && !isExpanded
                ? 300
                : contentRef.current?.scrollHeight,
          }}
          transition={{
            duration: 0.3,
            ease: "easeInOut",
          }}
        >
          <ScrollArea dir="ltr" className="w-full ">
            {childWithRef}
            <ScrollBar orientation="horizontal" />
          </ScrollArea>
        </motion.div>
        {shouldCollapse && (
          <div
            className={cn(
              "absolute bottom-0 z-10 left-0 right-0 flex justify-center p-1 pt-8",
              !isExpanded && "pointer-events-none"
            )}
          >
            {/* 渐变遮罩层 */}
            <div
              className={cn(
                "absolute inset-0 bg-linear-to-t h-[100px] from-[#EDEDED] via-[#EDEDED]/80 to-transparent",
                "transition-opacity duration-300",
                isExpanded ? "opacity-0" : "opacity-100"
              )}
            />
            <button
              onClick={toggleExpanded}
              className={cn(
                buttonVariants({ variant: "ghost", size: "sm" }),
                "w-fit relative mb-3 z-10 pointer-events-auto cursor-pointer backdrop-blur-sm px-2 py-1 gap-1",
                !isExpanded && "bg-white/60 hover:bg-white/80"
              )}
            >
              {isExpanded ? (
                <IconChevronUp className="w-4 h-4" />
              ) : (
                <IconChevronDown className="w-4 h-4" />
              )}
              {isExpanded ? "折叠" : "展开"}
            </button>
          </div>
        )}
      </figure>
    );
  }
);

CodeBlock.displayName = "CodeBlock";

function CopyButton({
  className,
  onCopy,
  ...props
}: ButtonHTMLAttributes<HTMLButtonElement> & {
  onCopy: () => void;
}) {
  const [checked, onClick] = useCopyButton(onCopy);

  return (
    <button
      type="button"
      className={cn(
        buttonVariants({
          variant: "ghost",
          size: "icon-sm",
        }),
        "transition-opacity group-hover:opacity-100 [&_svg]:size-3.5 cursor-pointer",
        className
      )}
      aria-label={checked ? "Copied Text" : "Copy Text"}
      onClick={onClick}
      {...props}
    >
      <Check className={cn("transition-transform", !checked && "scale-0")} />
      <Copy
        className={cn("absolute transition-transform", checked && "scale-0")}
      />
    </button>
  );
}

function ExpandButton({
  isExpanded,
  toggleExpanded,
}: {
  isExpanded: boolean;
  toggleExpanded: () => void;
}) {
  return (
    <button
      onClick={toggleExpanded}
      className={cn(
        buttonVariants({ variant: "ghost", size: "icon-sm" }),
        "transition-opacity cursor-pointer"
      )}
      aria-label={isExpanded ? "Collapse code block" : "Expand code block"}
    >
      {isExpanded ? (
        <IconChevronUp className="w-4 h-4" />
      ) : (
        <IconChevronDown className="w-4 h-4" />
      )}
    </button>
  );
}
